<?php

// this file is automatically generated by kickass-libexec scripts...

// you can change the name but not the code...
define( 'CCCDB_NAME', 'CCC Database' );
define( 'CCCDB_CODE', 'cccdb' );

//define( 'CCCDB_VERSION', '0.1.13' );
define( 'CCCDB_VERSION_MAJOR', 0 );
define( 'CCCDB_VERSION_MINOR', 1 );
define( 'CCCDB_VERSION_PATCH', 13 );

define(
  'CCCDB_SVN_DATE',
  '$Date: 2024-10-21 14:56:03 +1100 (Mon, 21 Oct 2024) $'
);
define( 'CCCDB_SVN_REVISION', '$Revision: 122510925 $' );
define( 'CCCDB_SVN_AUTHOR', '$Author: jj5 $' );

define( 'CCCDB_GIT_DATE', '2024-10-21 14:56:03 +1100 (Mon, 21 Oct 2024)' );
